import type {
  ServiceCall,
  Task,
  Customer,
  Site,
  Employee,
  TaskGroup,
} from "./types/service-call";

// Mock Employees
export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    name: "Jean Tremblay",
    email: "jean.tremblay@noxe.ca",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jean",
    position: "Senior Technician",
  },
  {
    id: "emp-2",
    name: "Marie Gagnon",
    email: "marie.gagnon@noxe.ca",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marie",
    position: "Field Technician",
  },
  {
    id: "emp-3",
    name: "Pierre Lavoie",
    email: "pierre.lavoie@noxe.ca",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pierre",
    position: "Network Specialist",
  },
  {
    id: "emp-4",
    name: "Sophie Roy",
    email: "sophie.roy@noxe.ca",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie",
    position: "Project Manager",
  },
];

// Mock Customers
export const mockCustomers: Customer[] = [
  {
    id: "cust-1",
    name: "Desjardins",
    email: "contact@desjardins.com",
  },
  {
    id: "cust-2",
    name: "Hydro-Québec",
    email: "support@hydroquebec.com",
  },
  {
    id: "cust-3",
    name: "Ville de Montréal",
    email: "info@montreal.ca",
  },
];

// Mock Sites
export const mockSites: Site[] = [
  {
    id: "site-1",
    name: "Siège Social - Place Desjardins",
    address: "150 rue des Commandeurs",
    city: "Lévis",
    customerId: "cust-1",
  },
  {
    id: "site-2",
    name: "Centre de données - Brossard",
    address: "8500 boul. Taschereau",
    city: "Brossard",
    customerId: "cust-1",
  },
  {
    id: "site-3",
    name: "Centrale Beauharnois",
    address: "80 rue Edgar",
    city: "Beauharnois",
    customerId: "cust-2",
  },
  {
    id: "site-4",
    name: "Hôtel de Ville",
    address: "275 rue Notre-Dame Est",
    city: "Montréal",
    customerId: "cust-3",
  },
];

// Mock Tasks for SC-1 (Network Connectivity Issues)
// Diagnostics Group Tasks
const sc1DiagnosticsTasks: Task[] = [
  {
    id: "task-1",
    name: "Diagnose network connectivity issue",
    description: "Server room switches reporting intermittent packet loss",
    status: "done",
    column: "done",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[2]],
    plannedTime: 2,
    timeEntries: [
      {
        id: "te-1",
        taskId: "task-1",
        employeeId: "emp-3",
        employee: mockEmployees[2],
        date: "2024-01-15",
        hours: 1.5,
        description: "Diagnosed faulty switch port",
        billable: true,
      },
    ],
    materials: [],
    startDate: "2024-01-15",
    dueDate: "2024-01-15",
    createdAt: "2024-01-14T10:00:00Z",
    updatedAt: "2024-01-15T14:30:00Z",
  },
  {
    id: "task-1b",
    name: "Run cable diagnostics",
    description: "Use cable tester to verify all patch cables in affected rack",
    status: "done",
    column: "done",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[1]],
    plannedTime: 1,
    timeEntries: [
      {
        id: "te-1b",
        taskId: "task-1b",
        employeeId: "emp-2",
        employee: mockEmployees[1],
        date: "2024-01-15",
        hours: 0.75,
        description: "Tested all 24 patch cables, found 2 faulty",
        billable: true,
      },
    ],
    materials: [],
    startDate: "2024-01-15",
    dueDate: "2024-01-15",
    createdAt: "2024-01-14T10:30:00Z",
    updatedAt: "2024-01-15T15:00:00Z",
  },
  {
    id: "task-1c",
    name: "Document network topology",
    description: "Update network diagram with current configuration",
    status: "in_progress",
    column: "in_progress",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[2]],
    plannedTime: 2,
    timeEntries: [],
    materials: [],
    dueDate: "2024-01-17",
    createdAt: "2024-01-15T16:00:00Z",
    updatedAt: "2024-01-15T16:00:00Z",
  },
];

// Hardware Repair Group Tasks
const sc1HardwareRepairTasks: Task[] = [
  {
    id: "task-2",
    name: "Replace faulty network switch",
    description: "Replace Cisco switch in rack 3, row 2",
    status: "in_progress",
    column: "in_progress",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[0], mockEmployees[2]],
    plannedTime: 4,
    timeEntries: [
      {
        id: "te-2",
        taskId: "task-2",
        employeeId: "emp-1",
        employee: mockEmployees[0],
        date: "2024-01-16",
        hours: 2,
        description: "Started switch replacement",
        billable: true,
      },
    ],
    materials: [
      {
        id: "mat-1",
        taskId: "task-2",
        name: "Cisco Catalyst 9200",
        quantity: 1,
        unitCost: 3500,
        totalCost: 3500,
        status: "ordered",
      },
    ],
    startDate: "2024-01-16",
    dueDate: "2024-01-17",
    createdAt: "2024-01-15T15:00:00Z",
    updatedAt: "2024-01-16T12:00:00Z",
  },
  {
    id: "task-2b",
    name: "Replace faulty patch cables",
    description: "Replace 2 damaged Cat6 cables identified during diagnostics",
    status: "done",
    column: "done",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[1]],
    plannedTime: 0.5,
    timeEntries: [
      {
        id: "te-2b",
        taskId: "task-2b",
        employeeId: "emp-2",
        employee: mockEmployees[1],
        date: "2024-01-16",
        hours: 0.5,
        description: "Replaced 2 faulty patch cables",
        billable: true,
      },
    ],
    materials: [
      {
        id: "mat-2b",
        taskId: "task-2b",
        name: "Cat6 Patch Cable 3m",
        quantity: 2,
        unitCost: 15,
        totalCost: 30,
        status: "used",
      },
    ],
    startDate: "2024-01-16",
    dueDate: "2024-01-16",
    createdAt: "2024-01-16T08:00:00Z",
    updatedAt: "2024-01-16T10:00:00Z",
  },
  {
    id: "task-2c",
    name: "Install cable management",
    description: "Add cable management arms and organize cables in rack 3",
    status: "todo",
    column: "todo",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[1]],
    plannedTime: 2,
    timeEntries: [],
    materials: [
      {
        id: "mat-2c",
        taskId: "task-2c",
        name: "Cable Management Arm",
        quantity: 4,
        unitCost: 45,
        totalCost: 180,
        status: "ordered",
      },
    ],
    dueDate: "2024-01-18",
    createdAt: "2024-01-16T12:00:00Z",
    updatedAt: "2024-01-16T12:00:00Z",
  },
];

// Configuration Group Tasks
const sc1ConfigurationTasks: Task[] = [
  {
    id: "task-3",
    name: "Configure and test new switch",
    description: "Apply standard config and verify connectivity",
    status: "todo",
    column: "todo",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[2]],
    plannedTime: 3,
    timeEntries: [],
    materials: [],
    dueDate: "2024-01-18",
    createdAt: "2024-01-15T15:30:00Z",
    updatedAt: "2024-01-15T15:30:00Z",
  },
  {
    id: "task-3b",
    name: "Configure VLAN settings",
    description: "Apply VLAN configuration matching existing network segmentation",
    status: "backlog",
    column: "backlog",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[2]],
    plannedTime: 1.5,
    timeEntries: [],
    materials: [],
    dueDate: "2024-01-18",
    createdAt: "2024-01-15T15:45:00Z",
    updatedAt: "2024-01-15T15:45:00Z",
  },
  {
    id: "task-3c",
    name: "Update monitoring system",
    description: "Add new switch to SNMP monitoring and alert system",
    status: "backlog",
    column: "backlog",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[3]],
    plannedTime: 1,
    timeEntries: [],
    materials: [],
    dueDate: "2024-01-19",
    createdAt: "2024-01-15T16:00:00Z",
    updatedAt: "2024-01-15T16:00:00Z",
  },
  {
    id: "task-3d",
    name: "Verify failover configuration",
    description: "Test redundancy and failover with backup switch",
    status: "backlog",
    column: "backlog",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[2], mockEmployees[0]],
    plannedTime: 2,
    timeEntries: [],
    materials: [],
    dueDate: "2024-01-19",
    createdAt: "2024-01-15T16:15:00Z",
    updatedAt: "2024-01-15T16:15:00Z",
  },
];

// Mock Tasks for SC-2 (Security Camera Installation)
// Camera Installation Group Tasks
const sc2CameraInstallationTasks: Task[] = [
  {
    id: "task-4",
    name: "Install security cameras - Entrance",
    description: "Mount and configure 4 PTZ cameras at main entrance",
    status: "todo",
    column: "todo",
    serviceCallId: "sc-2",
    siteId: "site-3",
    site: mockSites[2],
    assignedEmployees: [mockEmployees[1]],
    plannedTime: 6,
    timeEntries: [],
    materials: [
      {
        id: "mat-2",
        taskId: "task-4",
        name: "Hikvision PTZ Camera",
        quantity: 4,
        unitCost: 850,
        totalCost: 3400,
        status: "estimated",
      },
      {
        id: "mat-3",
        taskId: "task-4",
        name: "Cat6 Cable (100m)",
        quantity: 2,
        unitCost: 120,
        totalCost: 240,
        status: "estimated",
      },
    ],
    dueDate: "2024-01-25",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "task-4b",
    name: "Run cable conduits",
    description: "Install weatherproof conduits from entrance to server room",
    status: "in_progress",
    column: "in_progress",
    serviceCallId: "sc-2",
    siteId: "site-3",
    site: mockSites[2],
    assignedEmployees: [mockEmployees[0], mockEmployees[1]],
    plannedTime: 4,
    timeEntries: [
      {
        id: "te-4b",
        taskId: "task-4b",
        employeeId: "emp-1",
        employee: mockEmployees[0],
        date: "2024-01-21",
        hours: 3,
        description: "Installed 50m of outdoor conduit",
        billable: true,
      },
    ],
    materials: [
      {
        id: "mat-4b",
        taskId: "task-4b",
        name: "PVC Conduit 25mm",
        quantity: 60,
        unitCost: 8,
        totalCost: 480,
        status: "used",
      },
    ],
    startDate: "2024-01-21",
    dueDate: "2024-01-23",
    createdAt: "2024-01-10T09:15:00Z",
    updatedAt: "2024-01-21T16:00:00Z",
  },
  {
    id: "task-4c",
    name: "Mount camera brackets",
    description: "Install heavy-duty brackets for PTZ cameras",
    status: "done",
    column: "done",
    serviceCallId: "sc-2",
    siteId: "site-3",
    site: mockSites[2],
    assignedEmployees: [mockEmployees[1]],
    plannedTime: 2,
    timeEntries: [
      {
        id: "te-4c",
        taskId: "task-4c",
        employeeId: "emp-2",
        employee: mockEmployees[1],
        date: "2024-01-20",
        hours: 2.5,
        description: "Installed 4 camera brackets at entrance",
        billable: true,
      },
    ],
    materials: [
      {
        id: "mat-4c",
        taskId: "task-4c",
        name: "PTZ Bracket Heavy Duty",
        quantity: 4,
        unitCost: 125,
        totalCost: 500,
        status: "used",
      },
    ],
    startDate: "2024-01-20",
    dueDate: "2024-01-20",
    createdAt: "2024-01-10T09:30:00Z",
    updatedAt: "2024-01-20T17:00:00Z",
  },
];

// NVR Setup Group Tasks
const sc2NvrSetupTasks: Task[] = [
  {
    id: "task-5",
    name: "Configure NVR System",
    description: "Setup NVR and connect all cameras",
    status: "backlog",
    column: "backlog",
    serviceCallId: "sc-2",
    siteId: "site-3",
    site: mockSites[2],
    assignedEmployees: [],
    plannedTime: 4,
    timeEntries: [],
    materials: [
      {
        id: "mat-4",
        taskId: "task-5",
        name: "Hikvision NVR 16CH",
        quantity: 1,
        unitCost: 1200,
        totalCost: 1200,
        status: "estimated",
      },
    ],
    dueDate: "2024-01-26",
    createdAt: "2024-01-10T09:30:00Z",
    updatedAt: "2024-01-10T09:30:00Z",
  },
  {
    id: "task-5b",
    name: "Install NVR in server rack",
    description: "Mount NVR unit and connect to network",
    status: "backlog",
    column: "backlog",
    serviceCallId: "sc-2",
    siteId: "site-3",
    site: mockSites[2],
    assignedEmployees: [mockEmployees[0]],
    plannedTime: 1.5,
    timeEntries: [],
    materials: [
      {
        id: "mat-5b",
        taskId: "task-5b",
        name: "Rack Mount Kit",
        quantity: 1,
        unitCost: 85,
        totalCost: 85,
        status: "estimated",
      },
    ],
    dueDate: "2024-01-25",
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "task-5c",
    name: "Configure remote access",
    description: "Setup secure remote viewing for security team",
    status: "backlog",
    column: "backlog",
    serviceCallId: "sc-2",
    siteId: "site-3",
    site: mockSites[2],
    assignedEmployees: [mockEmployees[2]],
    plannedTime: 2,
    timeEntries: [],
    materials: [],
    dueDate: "2024-01-27",
    createdAt: "2024-01-10T10:15:00Z",
    updatedAt: "2024-01-10T10:15:00Z",
  },
  {
    id: "task-5d",
    name: "Train security staff",
    description: "Provide training on NVR operation and camera controls",
    status: "backlog",
    column: "backlog",
    serviceCallId: "sc-2",
    siteId: "site-3",
    site: mockSites[2],
    assignedEmployees: [mockEmployees[3]],
    plannedTime: 3,
    timeEntries: [],
    materials: [],
    dueDate: "2024-01-27",
    createdAt: "2024-01-10T10:30:00Z",
    updatedAt: "2024-01-10T10:30:00Z",
  },
];

// SC-3 Tasks (UPS Battery)
const sc3Tasks: Task[] = [
  {
    id: "task-6",
    name: "Repair server UPS",
    description: "UPS showing battery fault, needs battery replacement",
    status: "todo",
    column: "todo",
    serviceCallId: "sc-3",
    siteId: "site-2",
    site: mockSites[1],
    assignedEmployees: [mockEmployees[0]],
    plannedTime: 2,
    timeEntries: [],
    materials: [
      {
        id: "mat-5",
        taskId: "task-6",
        name: "APC RBC Battery Pack",
        quantity: 2,
        unitCost: 450,
        totalCost: 900,
        status: "ordered",
      },
    ],
    dueDate: "2024-01-20",
    createdAt: "2024-01-17T08:00:00Z",
    updatedAt: "2024-01-17T08:00:00Z",
  },
];

// Combine all tasks
export const mockTasks: Task[] = [
  ...sc1DiagnosticsTasks,
  ...sc1HardwareRepairTasks,
  ...sc1ConfigurationTasks,
  ...sc2CameraInstallationTasks,
  ...sc2NvrSetupTasks,
  ...sc3Tasks,
];

// Mock Service Calls
export const mockServiceCalls: ServiceCall[] = [
  {
    id: "sc-1",
    title: "Network Connectivity Issues - Server Room",
    description:
      "Multiple servers experiencing intermittent network drops. Users reporting slow access to file shares and internal applications.",
    status: "in_progress",
    priority: "high",
    customerId: "cust-1",
    customer: mockCustomers[0],
    siteId: "site-1",
    site: mockSites[0],
    startDate: "2024-01-14",
    createdAt: "2024-01-14T09:30:00Z",
    updatedAt: "2024-01-16T12:00:00Z",
    requesterId: "cust-1",
    issueType: "Network",
    equipmentType: "Switch",
    tasks: [...sc1DiagnosticsTasks, ...sc1HardwareRepairTasks, ...sc1ConfigurationTasks],
    taskGroups: [
      {
        id: "tg-diag",
        name: "Diagnostics",
        serviceCallId: "sc-1",
        tasks: sc1DiagnosticsTasks,
      },
      {
        id: "tg-repair",
        name: "Hardware Repair",
        serviceCallId: "sc-1",
        tasks: sc1HardwareRepairTasks,
      },
      {
        id: "tg-config",
        name: "Configuration",
        serviceCallId: "sc-1",
        tasks: sc1ConfigurationTasks,
      },
    ],
    summary: {
      predictedMaterial: 3710,
      estimatedSellPrice: 5500,
      estimatedCost: 3800,
      realCost: 2100,
      realSellPrice: 0,
    },
    clientPO: "PO-2024-0142",
  },
  {
    id: "sc-2",
    title: "Security Camera Installation - Main Entrance",
    description:
      "Install new PTZ cameras at main entrance per security upgrade project. Includes NVR setup and configuration.",
    status: "open",
    priority: "medium",
    customerId: "cust-2",
    customer: mockCustomers[1],
    siteId: "site-3",
    site: mockSites[2],
    startDate: "2024-01-20",
    endDate: "2024-01-27",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-10T09:30:00Z",
    issueType: "Installation",
    equipmentType: "Camera",
    tasks: [...sc2CameraInstallationTasks, ...sc2NvrSetupTasks],
    taskGroups: [
      {
        id: "tg-1",
        name: "Camera Installation",
        serviceCallId: "sc-2",
        tasks: sc2CameraInstallationTasks,
      },
      {
        id: "tg-2",
        name: "NVR Setup",
        serviceCallId: "sc-2",
        tasks: sc2NvrSetupTasks,
      },
    ],
    summary: {
      predictedMaterial: 5905,
      estimatedSellPrice: 8500,
      estimatedCost: 6200,
      realCost: 980,
      realSellPrice: 0,
    },
    clientPO: "PO-HQ-2024-089",
  },
  {
    id: "sc-3",
    title: "UPS Battery Replacement",
    description:
      "Data center UPS showing battery fault alarm. Critical - need to replace before batteries fail completely.",
    status: "open",
    priority: "urgent",
    customerId: "cust-1",
    customer: mockCustomers[0],
    siteId: "site-2",
    site: mockSites[1],
    startDate: "2024-01-17",
    createdAt: "2024-01-17T07:45:00Z",
    updatedAt: "2024-01-17T08:00:00Z",
    issueType: "Maintenance",
    equipmentType: "UPS",
    tasks: sc3Tasks,
    summary: {
      predictedMaterial: 900,
      estimatedSellPrice: 1800,
      estimatedCost: 1200,
      realCost: 0,
      realSellPrice: 0,
    },
  },
  {
    id: "sc-4",
    title: "Access Control System Troubleshooting",
    description:
      "Badge readers at parking garage not reading employee cards. System showing communication errors.",
    status: "resolved",
    priority: "medium",
    customerId: "cust-3",
    customer: mockCustomers[2],
    siteId: "site-4",
    site: mockSites[3],
    startDate: "2024-01-08",
    endDate: "2024-01-10",
    createdAt: "2024-01-08T14:00:00Z",
    updatedAt: "2024-01-10T16:30:00Z",
    issueType: "Troubleshooting",
    equipmentType: "Access Control",
    tasks: [],
    summary: {
      predictedMaterial: 0,
      estimatedSellPrice: 1200,
      estimatedCost: 800,
      realCost: 750,
      realSellPrice: 1200,
    },
    clientPO: "MTL-2024-00234",
  },
  {
    id: "sc-5",
    title: "Fiber Optic Cable Repair",
    description:
      "Construction accidentally cut underground fiber connection between buildings A and B.",
    status: "closed",
    priority: "urgent",
    customerId: "cust-2",
    customer: mockCustomers[1],
    siteId: "site-3",
    site: mockSites[2],
    startDate: "2024-01-02",
    endDate: "2024-01-03",
    createdAt: "2024-01-02T06:30:00Z",
    updatedAt: "2024-01-05T10:00:00Z",
    issueType: "Emergency Repair",
    equipmentType: "Fiber",
    tasks: [],
    summary: {
      predictedMaterial: 2500,
      estimatedSellPrice: 6500,
      estimatedCost: 4200,
      realCost: 4100,
      realSellPrice: 6500,
    },
    clientPO: "HQ-EMG-2024-001",
  },
];

// Helper to get service call with populated relations
export function getServiceCallById(id: string): ServiceCall | undefined {
  return mockServiceCalls.find((sc) => sc.id === id);
}

// Helper to get tasks by service call
export function getTasksByServiceCallId(serviceCallId: string): Task[] {
  return mockTasks.filter((t) => t.serviceCallId === serviceCallId);
}
