import type {
  ServiceCall,
  Task,
  Customer,
  Site,
  Employee,
  TaskGroup,
} from "./types/service-call";

// Mock Employees
export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    name: "Jean Tremblay",
    email: "jean.tremblay@noxe.ca",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jean",
    position: "Senior Technician",
  },
  {
    id: "emp-2",
    name: "Marie Gagnon",
    email: "marie.gagnon@noxe.ca",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marie",
    position: "Field Technician",
  },
  {
    id: "emp-3",
    name: "Pierre Lavoie",
    email: "pierre.lavoie@noxe.ca",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pierre",
    position: "Network Specialist",
  },
  {
    id: "emp-4",
    name: "Sophie Roy",
    email: "sophie.roy@noxe.ca",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie",
    position: "Project Manager",
  },
];

// Mock Customers
export const mockCustomers: Customer[] = [
  {
    id: "cust-1",
    name: "Desjardins",
    email: "contact@desjardins.com",
  },
  {
    id: "cust-2",
    name: "Hydro-Québec",
    email: "support@hydroquebec.com",
  },
  {
    id: "cust-3",
    name: "Ville de Montréal",
    email: "info@montreal.ca",
  },
];

// Mock Sites
export const mockSites: Site[] = [
  {
    id: "site-1",
    name: "Siège Social - Place Desjardins",
    address: "150 rue des Commandeurs",
    city: "Lévis",
    customerId: "cust-1",
  },
  {
    id: "site-2",
    name: "Centre de données - Brossard",
    address: "8500 boul. Taschereau",
    city: "Brossard",
    customerId: "cust-1",
  },
  {
    id: "site-3",
    name: "Centrale Beauharnois",
    address: "80 rue Edgar",
    city: "Beauharnois",
    customerId: "cust-2",
  },
  {
    id: "site-4",
    name: "Hôtel de Ville",
    address: "275 rue Notre-Dame Est",
    city: "Montréal",
    customerId: "cust-3",
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: "task-1",
    name: "Diagnose network connectivity issue",
    description: "Server room switches reporting intermittent packet loss",
    status: "done",
    column: "done",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[2]],
    plannedTime: 2,
    timeEntries: [
      {
        id: "te-1",
        taskId: "task-1",
        employeeId: "emp-3",
        employee: mockEmployees[2],
        date: "2024-01-15",
        hours: 1.5,
        description: "Diagnosed faulty switch port",
        billable: true,
      },
    ],
    materials: [],
    startDate: "2024-01-15",
    dueDate: "2024-01-15",
    createdAt: "2024-01-14T10:00:00Z",
    updatedAt: "2024-01-15T14:30:00Z",
  },
  {
    id: "task-2",
    name: "Replace faulty network switch",
    description: "Replace Cisco switch in rack 3, row 2",
    status: "in_progress",
    column: "in_progress",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[0], mockEmployees[2]],
    plannedTime: 4,
    timeEntries: [
      {
        id: "te-2",
        taskId: "task-2",
        employeeId: "emp-1",
        employee: mockEmployees[0],
        date: "2024-01-16",
        hours: 2,
        description: "Started switch replacement",
        billable: true,
      },
    ],
    materials: [
      {
        id: "mat-1",
        taskId: "task-2",
        name: "Cisco Catalyst 9200",
        quantity: 1,
        unitCost: 3500,
        totalCost: 3500,
        status: "ordered",
      },
    ],
    startDate: "2024-01-16",
    dueDate: "2024-01-17",
    createdAt: "2024-01-15T15:00:00Z",
    updatedAt: "2024-01-16T12:00:00Z",
  },
  {
    id: "task-3",
    name: "Configure and test new switch",
    description: "Apply standard config and verify connectivity",
    status: "todo",
    column: "todo",
    serviceCallId: "sc-1",
    siteId: "site-1",
    site: mockSites[0],
    assignedEmployees: [mockEmployees[2]],
    plannedTime: 3,
    timeEntries: [],
    materials: [],
    dueDate: "2024-01-18",
    createdAt: "2024-01-15T15:30:00Z",
    updatedAt: "2024-01-15T15:30:00Z",
  },
  {
    id: "task-4",
    name: "Install security cameras - Entrance",
    description: "Mount and configure 4 PTZ cameras at main entrance",
    status: "backlog",
    column: "backlog",
    serviceCallId: "sc-2",
    siteId: "site-3",
    site: mockSites[2],
    assignedEmployees: [mockEmployees[1]],
    plannedTime: 6,
    timeEntries: [],
    materials: [
      {
        id: "mat-2",
        taskId: "task-4",
        name: "Hikvision PTZ Camera",
        quantity: 4,
        unitCost: 850,
        totalCost: 3400,
        status: "estimated",
      },
      {
        id: "mat-3",
        taskId: "task-4",
        name: "Cat6 Cable (100m)",
        quantity: 2,
        unitCost: 120,
        totalCost: 240,
        status: "estimated",
      },
    ],
    dueDate: "2024-01-25",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "task-5",
    name: "Configure NVR System",
    description: "Setup NVR and connect all cameras",
    status: "backlog",
    column: "backlog",
    serviceCallId: "sc-2",
    siteId: "site-3",
    site: mockSites[2],
    assignedEmployees: [],
    plannedTime: 4,
    timeEntries: [],
    materials: [
      {
        id: "mat-4",
        taskId: "task-5",
        name: "Hikvision NVR 16CH",
        quantity: 1,
        unitCost: 1200,
        totalCost: 1200,
        status: "estimated",
      },
    ],
    dueDate: "2024-01-26",
    createdAt: "2024-01-10T09:30:00Z",
    updatedAt: "2024-01-10T09:30:00Z",
  },
  {
    id: "task-6",
    name: "Repair server UPS",
    description: "UPS showing battery fault, needs battery replacement",
    status: "todo",
    column: "todo",
    serviceCallId: "sc-3",
    siteId: "site-2",
    site: mockSites[1],
    assignedEmployees: [mockEmployees[0]],
    plannedTime: 2,
    timeEntries: [],
    materials: [
      {
        id: "mat-5",
        taskId: "task-6",
        name: "APC RBC Battery Pack",
        quantity: 2,
        unitCost: 450,
        totalCost: 900,
        status: "ordered",
      },
    ],
    dueDate: "2024-01-20",
    createdAt: "2024-01-17T08:00:00Z",
    updatedAt: "2024-01-17T08:00:00Z",
  },
];

// Mock Service Calls
export const mockServiceCalls: ServiceCall[] = [
  {
    id: "sc-1",
    title: "Network Connectivity Issues - Server Room",
    description:
      "Multiple servers experiencing intermittent network drops. Users reporting slow access to file shares and internal applications.",
    status: "in_progress",
    priority: "high",
    customerId: "cust-1",
    customer: mockCustomers[0],
    siteId: "site-1",
    site: mockSites[0],
    startDate: "2024-01-14",
    createdAt: "2024-01-14T09:30:00Z",
    updatedAt: "2024-01-16T12:00:00Z",
    requesterId: "cust-1",
    issueType: "Network",
    equipmentType: "Switch",
    tasks: mockTasks.filter((t) => t.serviceCallId === "sc-1"),
    summary: {
      predictedMaterial: 3500,
      estimatedSellPrice: 5500,
      estimatedCost: 3800,
      realCost: 2100,
      realSellPrice: 0,
    },
    clientPO: "PO-2024-0142",
  },
  {
    id: "sc-2",
    title: "Security Camera Installation - Main Entrance",
    description:
      "Install new PTZ cameras at main entrance per security upgrade project. Includes NVR setup and configuration.",
    status: "open",
    priority: "medium",
    customerId: "cust-2",
    customer: mockCustomers[1],
    siteId: "site-3",
    site: mockSites[2],
    startDate: "2024-01-20",
    endDate: "2024-01-27",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-10T09:30:00Z",
    issueType: "Installation",
    equipmentType: "Camera",
    tasks: mockTasks.filter((t) => t.serviceCallId === "sc-2"),
    taskGroups: [
      {
        id: "tg-1",
        name: "Camera Installation",
        serviceCallId: "sc-2",
        tasks: mockTasks.filter((t) => t.id === "task-4"),
      },
      {
        id: "tg-2",
        name: "NVR Setup",
        serviceCallId: "sc-2",
        tasks: mockTasks.filter((t) => t.id === "task-5"),
      },
    ],
    summary: {
      predictedMaterial: 4840,
      estimatedSellPrice: 8500,
      estimatedCost: 6200,
      realCost: 0,
      realSellPrice: 0,
    },
    clientPO: "PO-HQ-2024-089",
  },
  {
    id: "sc-3",
    title: "UPS Battery Replacement",
    description:
      "Data center UPS showing battery fault alarm. Critical - need to replace before batteries fail completely.",
    status: "open",
    priority: "urgent",
    customerId: "cust-1",
    customer: mockCustomers[0],
    siteId: "site-2",
    site: mockSites[1],
    startDate: "2024-01-17",
    createdAt: "2024-01-17T07:45:00Z",
    updatedAt: "2024-01-17T08:00:00Z",
    issueType: "Maintenance",
    equipmentType: "UPS",
    tasks: mockTasks.filter((t) => t.serviceCallId === "sc-3"),
    summary: {
      predictedMaterial: 900,
      estimatedSellPrice: 1800,
      estimatedCost: 1200,
      realCost: 0,
      realSellPrice: 0,
    },
  },
  {
    id: "sc-4",
    title: "Access Control System Troubleshooting",
    description:
      "Badge readers at parking garage not reading employee cards. System showing communication errors.",
    status: "resolved",
    priority: "medium",
    customerId: "cust-3",
    customer: mockCustomers[2],
    siteId: "site-4",
    site: mockSites[3],
    startDate: "2024-01-08",
    endDate: "2024-01-10",
    createdAt: "2024-01-08T14:00:00Z",
    updatedAt: "2024-01-10T16:30:00Z",
    issueType: "Troubleshooting",
    equipmentType: "Access Control",
    tasks: [],
    summary: {
      predictedMaterial: 0,
      estimatedSellPrice: 1200,
      estimatedCost: 800,
      realCost: 750,
      realSellPrice: 1200,
    },
    clientPO: "MTL-2024-00234",
  },
  {
    id: "sc-5",
    title: "Fiber Optic Cable Repair",
    description:
      "Construction accidentally cut underground fiber connection between buildings A and B.",
    status: "closed",
    priority: "urgent",
    customerId: "cust-2",
    customer: mockCustomers[1],
    siteId: "site-3",
    site: mockSites[2],
    startDate: "2024-01-02",
    endDate: "2024-01-03",
    createdAt: "2024-01-02T06:30:00Z",
    updatedAt: "2024-01-05T10:00:00Z",
    issueType: "Emergency Repair",
    equipmentType: "Fiber",
    tasks: [],
    summary: {
      predictedMaterial: 2500,
      estimatedSellPrice: 6500,
      estimatedCost: 4200,
      realCost: 4100,
      realSellPrice: 6500,
    },
    clientPO: "HQ-EMG-2024-001",
  },
];

// Helper to get service call with populated relations
export function getServiceCallById(id: string): ServiceCall | undefined {
  return mockServiceCalls.find((sc) => sc.id === id);
}

// Helper to get tasks by service call
export function getTasksByServiceCallId(serviceCallId: string): Task[] {
  return mockTasks.filter((t) => t.serviceCallId === serviceCallId);
}
